### ISSUE TITLE
sidebar broke

### ISSUE THREAD

**Issue by cybr23** [Comfy-Themes/Discord#153]
the sidebar no longer holds the button for disable game activity, mic, deafen, and settings
![image](https://github.com/user-attachments/assets/cf60aba8-1f56-49d7-aaa0-a417cf71d7a5)

**Comment by ZineddineMessaoudi** [comment]
Hi, I had the same issue so I added this css rules in the comfy.theme.css file (you can edit it through the settings) : 

```css
.flex_dc333f.horizontal_dc333f.justifyStart_ec1a20.alignStretch_ec1a20.noWrap_ec1a20.buttons_b2ca13 {
  display: flex;
  flex-direction: column;
  margin-bottom: 100px;
  position: fixed;
  left: 20px;
}
```

Yet this is not exactly as it is supposed to be, if you have a lot of servers they will be under the settings panel but you can still scroll to access them.

Hope it can help you.

Have a great day.
