### ISSUE TITLE
The Close Icon doesn't exist or doesn't render/show itself

### ISSUE THREAD

**Issue by Arghadatta** [Comfy-Themes/Discord#98]
![image](https://user-images.githubusercontent.com/78955676/232309902-6e771bda-ebbc-4b69-a4b9-c3434d98b31b.png)
the picture before any text cause it would be self-explainatory.

i am using vencord and it is showing this problem.it also occured on replugged too.
i did restarting my client and also reloading the theme?
but it is happening since my first install.

@NYRI4 
sorry for pinging tho

**Comment by Redundakitties** [comment]
I think this might be an issue on your end unfortunately. I just tried this theme and the close icon renders for me.
```css

.winButtonClose-3Q8ZH5 {
  margin-right: 5px;
}
.winButtonClose-3Q8ZH5::after {
  padding: 6px;
  background-image: url("https://i.imgur.com/WAbJScJ.png");
  background-size: 100%;
}
.winButtonClose-3Q8ZH5:hover::after {
  background-image: url("https://i.imgur.com/ipwGE9a.png");
  background-size: 100%;
}
```
this looks like it's the code for the close button. Could it be that somehow your computer isn't able to access this imgur link? I'm not sure how much experience with CSS you have but if you copy and paste the main file into your quickCSS on vencord and then delete these lines it won't modify your close button and it should come back. Let me know if that works or I should explain any more.
